# Site settings
title:         pr4tt.com
email:         simon@pr4tt.com
author:        Simon David Pratt
description:   "Simon Pratt's blog"
url:           "http://blog.pr4tt.com"
google_analytics: 

# Build settings
gems: [jekyll-paginate]
paginate:      3
paginate_path: "/archives/page:num/"
markdown:      kramdown
markdown_ext:  "markdown,markup,mkdown,mkdn,mkd,md"

# Permalinks
permalink:     pretty
encoding:      UTF-8

# Kramdown
kramdown:  
  parse_block_html: true
