# Site settings
title: pr4tt.com
email: simon@pr4tt.com
author: Simon David Pratt
description: "Simon Pratt's blog"
baseurl: "http://spratt.github.io"
url: "http://spratt.github.io/"
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
